In [1]:
from google.cloud import bigquery
import pandas_gbq
%load_ext google.cloud.bigquery

# Set your default project here
pandas_gbq.context.project = 'snappy-boulder-378707'
pandas_gbq.context.dialect = 'standard'

import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")

import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../BigQuery/letsgo-snappy-boulder-378707-4b7d46801fd1.json"

# Construct a BigQuery client object.
client = bigquery.Client()

from statsmodels.formula.api import ols

In [2]:
%%bigquery audio_feature
SELECT * FROM snappy-boulder-378707.TrackClearInfo.AudioFeaturesTrain

Query is running:   0%|          |

Downloading:   0%|          |

In [3]:
ids = pd.read_csv("ids 2019.csv")
artists = pd.read_csv("artist2019.csv")

In [4]:
ids

,Unnamed: 0,track_id,album_id,artists_id
0,0,6EOKwHETwSkZ9gW2b6ASE0,65T18oWoikW2MAilg9j8lW,['4Ga1P7PMIsmqEZqhYZQgDo']
1,1,0a1LpYLrp1VNwEekoqFJx5,5eDB3cEFNX5W10auAjFPQk,['0kSazizYsGZQYKRfROiVb8']
2,2,1esVK0wgkpFJ31eHvHZ7M9,0sbwoolm9aZGBPBEqoU3CX,['3qNVuliS40BLgXGxhdBdqu']
3,3,1RgSs1Jy3QHiacsnMxAAL2,1fK3kyhjoaQBDofh8Ppfjl,['44T03OWDUjwDgg4IYgFCWi']
4,4,7zFBtYAVURF3bUVqEQ6UUu,2y2Nuvvw5xNDYOunTSsgf1,['2KC9Qb60EaY0kW4eH68vr3']
...,...,...,...,...
27653,27653,2YdyXJ9dZ3XxpB9oLBAgKj,5x8rzbS1fTG31aot2ivcEj,['18eJA6yngcgTKd80ogxfCs']
27654,27654,6tmCkgP4B4Tl333lKetzX8,22d1e9G3IQAa6pK3sV9S5j,['5FhnxR08tvAO0f4ixh3VFD']
27655,27655,3qZaFoWwuh5GRCmTyxbbXW,1lIpey9W9JZCQJuzWBGv4c,"['35LFDqRu6EmXgUqEWeh2j6', '4svvMm4TQnkphZJfhL..."
27656,27656,4GiMCIKbU6R1NKBEJAoWKX,0KqViwaI5HOvFU5Tys8sbm,['1bMzicd9EOrx6iGexZ0AbQ']
27657,27657,2bxmZTdcE3iSYGEu0gtmMk,1x7oZY9054zAg2MDf1K3KS,['56VhOZOF6hwqrbNYwkmcsH']

In [5]:
artists

,Unnamed: 0,track_id,id,name,followers,genres,popularity
0,0,6EOKwHETwSkZ9gW2b6ASE0,4Ga1P7PMIsmqEZqhYZQgDo,Lil Tecca,5814168,"['melodic rap', 'pluggnb', 'rap', 'trap', 'vir...",79
1,1,0a1LpYLrp1VNwEekoqFJx5,0kSazizYsGZQYKRfROiVb8,Coma,79,[],5
2,2,1esVK0wgkpFJ31eHvHZ7M9,3qNVuliS40BLgXGxhdBdqu,TAEYEON,2703917,"['k-pop', 'pop']",70
3,3,1RgSs1Jy3QHiacsnMxAAL2,44T03OWDUjwDgg4IYgFCWi,MARUV,287582,"['russian pop', 'ukrainian pop']",46
4,4,7zFBtYAVURF3bUVqEQ6UUu,2KC9Qb60EaY0kW4eH68vr3,ITZY,5263838,['k-pop girl group'],76
...,...,...,...,...,...,...,...
9533,9533,1l41tvs85mZdv9WuYmT2Tx,4Dm1MX4VPbtLssAQeBhHFo,Famke Louise,181785,"['dutch hip hop', 'dutch pop', 'dutch rap pop']",46
9534,9534,1l41tvs85mZdv9WuYmT2Tx,1EYdbYpGAuJy6uZo4sVMoM,Idaly,93441,"['dutch hip hop', 'dutch pop', 'dutch rap pop']",65
9535,9535,24vJxXMDQQfVIMkhaOj5oP,2kLUMm1KApZfFb90K0R6d6,Bernt Hulsker,715,[],16
9536,9536,24vJxXMDQQfVIMkhaOj5oP,4KOIqm3HfmXTHdFaxzbg6V,Den nye Mads Hansen,51,[],15
9537,9537,6VpKDxeqBuRMOhXz8QGkZZ,5VD5GCCQ2hh0m7ufVlmcue,Nicolay Ramm,16444,[],40

In [6]:
audio_feature

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,id,duration_ms,time_signature
0,0.707,0.883,0,-4.391,0,0.0904,0.5030,0.000002,0.0764,0.947,178.014,5AGkEX0nP1Pa9pVshupHBe,234607,4
1,0.546,0.285,0,-10.237,0,0.0339,0.2740,0.109000,0.0768,0.147,120.112,69HvmK75WgBbmh6aJsz84U,240000,3
2,0.193,0.322,0,-17.323,0,0.0300,0.3990,0.884000,0.1420,0.270,100.007,3jV2CmcxvOF5vvWM3Pyngf,185507,4
3,0.754,0.730,0,-3.169,0,0.0464,0.2380,0.000112,0.0891,0.274,154.044,0AoF4PffeD5NdvpiBihp6Q,178173,4
4,0.682,0.657,0,-7.258,0,0.0882,0.0855,0.023400,0.2170,0.386,115.058,1VeSIXPVrMqrpr8xOyUloh,187453,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164779,0.749,0.671,11,-7.741,1,0.0568,0.0446,0.000000,0.1010,0.120,113.077,0QetVR4wwvyiTezQeFNdeZ,256131,4
164780,0.731,0.867,11,-5.881,1,0.0320,0.0395,0.000000,0.0861,0.776,104.019,3cfOd4CMv2snFaKAnMdnvK,200373,4
164781,0.677,0.857,11,-3.995,1,0.3850,0.0210,0.000000,0.1610,0.787,87.599,0XCRGMDfxqOIl6TqGDcYoE,219500,4
164782,0.680,0.730,11,-6.175,1,0.0911,0.1290,0.000000,0.1010,0.385,91.988,5Rlcx4jMCAiiWd56e7VEZ5,232412,4
164783,0.542,0.643,11,-7.794,1,0.0293,0.4370,0.000000,0.1190,0.586,140.995,0wX322Hk65LZyzXqvFfDH7,201372,3

In [7]:
df = pd.merge(artists, audio_feature, how="inner", left_on="track_id", right_on="id")
df

,Unnamed: 0,track_id,id_x,name,followers,genres,popularity,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,id_y,duration_ms,time_signature
0,0,6EOKwHETwSkZ9gW2b6ASE0,4Ga1P7PMIsmqEZqhYZQgDo,Lil Tecca,5814168,"['melodic rap', 'pluggnb', 'rap', 'trap', 'vir...",79,0.745,0.642,7,...,0,0.2870,0.02040,0.000000,0.0658,0.226,179.974,6EOKwHETwSkZ9gW2b6ASE0,131240,4
1,1,0a1LpYLrp1VNwEekoqFJx5,0kSazizYsGZQYKRfROiVb8,Coma,79,[],5,0.539,0.499,11,...,0,0.0477,0.10300,0.000008,0.1060,0.140,148.900,0a1LpYLrp1VNwEekoqFJx5,222282,4
2,2,1esVK0wgkpFJ31eHvHZ7M9,3qNVuliS40BLgXGxhdBdqu,TAEYEON,2703917,"['k-pop', 'pop']",70,0.509,0.816,2,...,1,0.0612,0.22400,0.000000,0.2190,0.641,159.844,1esVK0wgkpFJ31eHvHZ7M9,191988,4
3,3,1RgSs1Jy3QHiacsnMxAAL2,44T03OWDUjwDgg4IYgFCWi,MARUV,287582,"['russian pop', 'ukrainian pop']",46,0.729,0.792,4,...,0,0.0334,0.03900,0.006220,0.1040,0.667,115.024,1RgSs1Jy3QHiacsnMxAAL2,171130,4
4,4,7zFBtYAVURF3bUVqEQ6UUu,2KC9Qb60EaY0kW4eH68vr3,ITZY,5263838,['k-pop girl group'],76,0.801,0.904,2,...,1,0.0834,0.03240,0.000031,0.1820,0.814,124.979,7zFBtYAVURF3bUVqEQ6UUu,191142,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9533,9533,1l41tvs85mZdv9WuYmT2Tx,4Dm1MX4VPbtLssAQeBhHFo,Famke Louise,181785,"['dutch hip hop', 'dutch pop', 'dutch rap pop']",46,0.759,0.594,4,...,0,0.1770,0.25400,0.001660,0.1060,0.330,180.010,1l41tvs85mZdv9WuYmT2Tx,195616,4
9534,9534,1l41tvs85mZdv9WuYmT2Tx,1EYdbYpGAuJy6uZo4sVMoM,Idaly,93441,"['dutch hip hop', 'dutch pop', 'dutch rap pop']",65,0.759,0.594,4,...,0,0.1770,0.25400,0.001660,0.1060,0.330,180.010,1l41tvs85mZdv9WuYmT2Tx,195616,4
9535,9535,24vJxXMDQQfVIMkhaOj5oP,2kLUMm1KApZfFb90K0R6d6,Bernt Hulsker,715,[],16,0.736,0.720,0,...,1,0.0603,0.08720,0.000000,0.3730,0.809,99.984,24vJxXMDQQfVIMkhaOj5oP,169216,4
9536,9536,24vJxXMDQQfVIMkhaOj5oP,4KOIqm3HfmXTHdFaxzbg6V,Den nye Mads Hansen,51,[],15,0.736,0.720,0,...,1,0.0603,0.08720,0.000000,0.3730,0.809,99.984,24vJxXMDQQfVIMkhaOj5oP,169216,4
9537,9537,6VpKDxeqBuRMOhXz8QGkZZ,5VD5GCCQ2hh0m7ufVlmcue,Nicolay Ramm,16444,[],40,0.662,0.826,10,...,1,0.0414,0.00456,0.000000,0.3350,0.406,125.019,6VpKDxeqBuRMOhXz8QGkZZ,177351,4

In [8]:
df.columns

Index(['Unnamed: 0', 'track_id', 'id_x', 'name', 'followers', 'genres',
       'popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'id_y', 'duration_ms', 'time_signature'],
      dtype='object')

## duplicate rows

In [9]:
df = df.drop(['Unnamed: 0', 'track_id', 'id_x', 'name', 'followers', 'id_y', 'duration_ms', 'time_signature'], axis=1)

In [16]:
newdf = pd.DataFrame(columns=df.columns)
newdf

Empty DataFrame
Columns: [genres, popularity, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo]
Index: []

In [29]:
for i in range(df.shape[0],100):
    row = df.iloc[i]
    print(row)
    genres = row[0].strip('][').split(', ')
    print(genres)
    others = row[1:]
    # new_row = pd.Series(genres[0]).append(others)
    for genre in genres:
        new_row = pd.Series(genre).append(others)
        print(new_row)
        newdf.append(new_row, ignore_index=True)

https://www.kaggle.com/code/arthurlees/spotify-song-attribute-analysis

In [ ]:
tracks = pd.read_excel("spotify_genre_final.xlsx")
tracks.head()

In [ ]:
tracks.shape

In [ ]:
# audio_feature.shape

In [ ]:
# df = pd.merge(tracks, audio_feature, on="id", how="inner")
# df.shape
df = tracks

In [ ]:
tracks["Genre"].value_counts()

In [ ]:
from sklearn.utils import shuffle
df = shuffle(df)
df.head()

In [ ]:
df.columns

In [ ]:
# df = df.drop(['Title', 'Album_cover_link', 'Artist', 'id', 'popularity', 'release_date',
#               'release_date_precision', 'total_tracks', 'int64_field_0', 'type', 'uri', 'track_href',
#               'analysis_url','uri', 'track_href', 'analysis_url'], axis = 1)
df = df.drop(['Title', 'Album_cover_link', 'Artist', 'id', 'release_date', 
              'release_date_precision', 'total_tracks', 'time_signature'],axis=1)
df

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop("Genre",axis=1), df["Genre"], test_size=0.2, random_state=42)

In [ ]:
X_train.shape

In [ ]:
X_test.shape

In [ ]:
y_train.shape

In [ ]:
cols = X_train.columns

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_st = scaler.fit_transform(X_train)
X_test_st = scaler.transform(X_test)

X_train_st = pd.DataFrame(X_train_st, columns=[cols])
X_test_st = pd.DataFrame(X_test_st, columns=[cols])

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC() 
svc.fit(X_train_st,y_train)
y_pred=svc.predict(X_test_st)
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))
# 0.5845